// GENERATED by scripts/media-thumbs.mjs — do not edit by hand.
// Large stills in media/ that have a -thumb.avif variant (longest side 1024),
// mapped to [fullWidth, thumbWidth] for srcset width descriptors.
export const MEDIA_THUMBS = new Map<string, [number, number]>([
	[
		'2005-05-01_oak_park_6th_grade_graduation-brian_and_kevin_smile_at_camera.avif',
		[1536, 1024],
	],
	['2008-06-10_create_your_own_adventure-plot_outline_diagram.avif', [2048, 1024]],
	[
		'2008-08-09_power_rangers_360_ii-premiere-backyward_projector_setup.avif',
		[1536, 768],
	],
	[
		'2008-08-15_power_rangers_360_ii-movie_poster_with_high_quality_image_and_no_characters.avif',
		[1638, 819],
	],
	[
		'2009-04-19_lawrence_high_school_film_festival-brian_and_kevin_in_front_of_theater.avif',
		[1365, 683],
	],
	[
		'2009-04-19_lawrence_high_school_film_festival-brian_close_shot_in_front_of_theater.avif',
		[2048, 1024],
	],
	[
		'2009-04-23_johnson_county_community_college_film_festival-brian_and_kevin_1.avif',
		[2048, 1024],
	],
	[
		'2009-04-23_johnson_county_community_college_film_festival-brian_and_kevin_2.avif',
		[2048, 1024],
	],
	[
		'2009-04-23_johnson_county_community_college_film_festival-brian_and_kevin_3.avif',
		[2048, 1024],
	],
	[
		'2009-04-23_johnson_county_community_college_film_festival-brian_and_kevin_4.avif',
		[2048, 1024],
	],
	[
		'2009-04-23_johnson_county_community_college_film_festival-brian_and_kevin_5.avif',
		[2048, 1024],
	],
	[
		'2009-04-23_johnson_county_community_college_film_festival-brian_and_kevin_6.avif',
		[2048, 1024],
	],
	[
		'2009-04-23_johnson_county_community_college_film_festival-brian_and_kevin_7.avif',
		[2048, 1024],
	],
	['2009-04-29_shawnee_mission_east_film_festival-kevin_and_brian_1.avif', [2048, 1024]],
	['2009-04-29_shawnee_mission_east_film_festival-kevin_and_brian_2.avif', [2048, 1024]],
	['2009-04-29_shawnee_mission_east_film_festival-kevin_and_brian_3.avif', [1365, 683]],
	['2009-04-29_shawnee_mission_east_film_festival-kevin_and_brian_4.avif', [1365, 683]],
	['2009-12-25_calamity-lego_movie_storyboard_still_frame.avif', [2048, 1024]],
	['2010-01-01_hunky_spunky_productions-website_design-home_page.avif', [1878, 1024]],
	[
		'2010-03-03_ksms_student_television_convention_trip-brian_kevin_wes.avif',
		[2048, 1024],
	],
	[
		'2010-03-03_ksms_student_television_convention_trip-ksms_group_photo.avif',
		[2048, 1024],
	],
	['2011-03-01_exposure-3d_camera_model_wireframe.avif', [2048, 1024]],
	['2011-03-01_exposure-camera_robot_mid_transformation_stillframe.avif', [1920, 1024]],
	['2011-03-01_exposure-film_poster.avif', [1638, 819]],
	['2011-03-01_exposure-film_storyboard.avif', [2048, 1024]],
	['2011-03-01_ksms_soccer_feature-behind_the_scenes_brian_filming.avif', [2048, 640]],
	[
		'2011-03-01_ksms_soccer_feature-behind_the_scenes_brian_filming_close_up.avif',
		[2048, 1024],
	],
	[
		'2011-03-12_ksms_block_party-will_it_break_video-behind_the_scenes-brian_filming_matthew_1.avif',
		[1362, 681],
	],
	[
		'2011-03-12_ksms_block_party-will_it_break_video-behind_the_scenes-brian_filming_matthew_2.avif',
		[1362, 681],
	],
	[
		'2011-03-12_ksms_block_party-will_it_break_video-behind_the_scenes-brian_setting_up_camera.avif',
		[1362, 681],
	],
	[
		'2011-03-12_ksms_block_party-will_it_break_video-behind_the_scenes-crew_packing_car.avif',
		[2048, 640],
	],
	[
		'2011-03-12_ksms_block_party-will_it_break_video-behind_the_scenes-scientists_smile_at_camera.avif',
		[2048, 1024],
	],
	[
		'2011-03-12_ksms_block_party-will_it_break_video-behind_the_scenes-scientists_smile_at_camera_with_friends.avif',
		[2048, 1024],
	],
	[
		'2011-04-17_lawrence_high_school_film_festival-brian_and_kevin_holding_award_outside_after_winning_1st_place_comedy.avif',
		[2048, 1024],
	],
	[
		'2011-08-19_brian_in_dorm_room_on_move_in_day_at_missouri_state_university.avif',
		[2048, 1024],
	],
	['2011-08-28_long_time_no_see-movie_poster.avif', [1568, 784]],
	['2011-08-28_xyz_news-iprez-film_snapshot_of_kevin_as_news_anchor.avif', [1920, 1024]],
	[
		'2012-01-16_tube_tape_commercial-camdolly-video_stillframe_using_dolly.avif',
		[1920, 1024],
	],
	[
		'2012-03-22_holy_cross_lutheran_church_tshirt_commericial-angel_appears_still_frame.avif',
		[1920, 1024],
	],
	['2012-05-01_premier_studios_summer_internship-interns_group_photo.avif', [2048, 1024]],
	[
		'2012-06-24_premier_studios_summer_internship-target_video_shoot_behind_the_scenes_1.avif',
		[2048, 1024],
	],
	[
		'2012-06-24_premier_studios_summer_internship-target_video_shoot_behind_the_scenes_2.avif',
		[2048, 1024],
	],
	[
		'2012-06-24_premier_studios_summer_internship-target_video_shoot_behind_the_scenes_3.avif',
		[2048, 1024],
	],
	[
		'2012-07-12_premier_studios_summer_internship-green_screen_shoot_1.avif',
		[2048, 1024],
	],
	[
		'2012-07-12_premier_studios_summer_internship-green_screen_shoot_2.avif',
		[2048, 1024],
	],
	[
		'2012-08-01_premier_studios_summer_intership-flash_mob_shoot_group_photo.avif',
		[1950, 1024],
	],
	['2013-02-23_schwikes_studios_pricing_graphics_for_website.avif', [1920, 1024]],
	[
		'2013-03-07_video_shoot_behind_the_scenes-camera_filming_green_screen_interview.avif',
		[2048, 1024],
	],
	[
		'2013-05-23_video_shoot_behind_the_scenes-filming_interview_at_house.avif',
		[2048, 1024],
	],
	['2013-05-29_hunky_spunky_production_movie_history_poster.avif', [1638, 819]],
	[
		'2013-05-30_video_shoot_behind_the_scenes-filming_green_screen_with_ample_lighting.avif',
		[2048, 1024],
	],
	[
		'2013-06-13_video_shoot_behind_the_scenes-filming_music_video_at_church_with_many_lights.avif',
		[2048, 1024],
	],
	[
		'2013-06-22_the_spunksters-live_show_behind_the_scenes_panorama_photo.avif',
		[2048, 1024],
	],
	['2013-06-22_the_spunksters-live_show_behind_the_scenes_photos_01.avif', [2048, 1024]],
	['2013-06-22_the_spunksters-live_show_behind_the_scenes_photos_02.avif', [1365, 683]],
	['2013-06-22_the_spunksters-live_show_behind_the_scenes_photos_03.avif', [2048, 1024]],
	['2013-06-22_the_spunksters-live_show_behind_the_scenes_photos_04.avif', [2048, 1024]],
	['2013-06-22_the_spunksters-live_show_behind_the_scenes_photos_05.avif', [2048, 1024]],
	['2013-06-22_the_spunksters-live_show_behind_the_scenes_photos_06.avif', [2048, 1024]],
	['2013-06-22_the_spunksters-live_show_behind_the_scenes_photos_07.avif', [1536, 768]],
	[
		'2013-09-17_video_shoot_behind_the_scenes-filming_dorm_talent_show.avif',
		[2048, 1024],
	],
	['2013-09-28_maggie_and_brian_wedding_video-stillframe_1.avif', [1920, 1024]],
	[
		'2013-09-28_video_shoot_behind_the_scenes-filming_wedding_group_photo.avif',
		[2048, 1024],
	],
	[
		'2013-11-09_video_shoot_behind_the_scenes-filming_cross_fit_workout_competition.avif',
		[2048, 1024],
	],
	['2013-12-15_new_computer_parts_on_table_for_new_computer_build.avif', [2048, 1024]],
	[
		'2014-02-22_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_093913.avif',
		[2048, 1024],
	],
	[
		'2014-02-22_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_095449.avif',
		[2048, 1024],
	],
	[
		'2014-03-01_video_shoot_behind_the_scenes-filming_wedding_at_big_church.avif',
		[2048, 1024],
	],
	[
		'2014-03-06_art_300_project-node-360_short_film-behind_the_scenes_01-four_go_pro_mount.avif',
		[2048, 1024],
	],
	[
		'2014-03-06_art_300_project-node-360_short_film-behind_the_scenes_02.avif',
		[2048, 1024],
	],
	[
		'2014-03-06_art_300_project-node-360_short_film-behind_the_scenes_03_four_gopro_mount_in_car.avif',
		[2048, 1024],
	],
	[
		'2014-03-06_art_300_project-node-360_short_film-behind_the_scenes_04.avif',
		[2048, 1024],
	],
	[
		'2014-03-06_art_300_project-node-360_short_film-behind_the_scenes_05-all_actors.avif',
		[2048, 640],
	],
	[
		'2014-03-06_art_300_project-node-360_short_film-behind_the_scenes_06.avif',
		[2048, 1024],
	],
	[
		'2014-03-06_art_300_project-node-360_short_film-behind_the_scenes_07.avif',
		[2048, 1024],
	],
	[
		'2014-03-18_art_300_project-node-360_short_film-website_home_page_with_additional_screenshots.avif',
		[1920, 1024],
	],
	['2014-03-18_art_300_project-node-360_short_film_panorama_camera_1.avif', [1440, 768]],
	['2014-03-18_art_300_project-node-360_short_film_panorama_camera_2.avif', [1440, 768]],
	['2014-03-18_art_300_project-node-360_short_film_panorama_camera_3.avif', [1440, 768]],
	['2014-03-18_art_300_project-node-360_short_film_panorama_camera_4.avif', [1440, 768]],
	[
		'2014-03-18_art_300_project-node-360_short_film_panorama_equirectangular.avif',
		[2048, 640],
	],
	[
		'2014-03-21_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_120858.avif',
		[2048, 1024],
	],
	[
		'2014-03-21_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_125906.avif',
		[2048, 1024],
	],
	[
		'2014-03-21_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_133051.avif',
		[2048, 1024],
	],
	[
		'2014-03-21_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_184420.avif',
		[2048, 1024],
	],
	[
		'2014-03-21_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_200723.avif',
		[2048, 1024],
	],
	[
		'2014-03-22_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_121722.avif',
		[2048, 1024],
	],
	[
		'2014-03-22_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_121746.avif',
		[2048, 1024],
	],
	[
		'2014-03-22_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_124155.avif',
		[2048, 1024],
	],
	[
		'2014-03-22_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_163203.avif',
		[2048, 1024],
	],
	[
		'2014-03-22_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_192230.avif',
		[2048, 1024],
	],
	[
		'2014-03-22_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_192756.avif',
		[2048, 1024],
	],
	[
		'2014-03-23_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_095102.avif',
		[2048, 1024],
	],
	[
		'2014-03-23_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_111947.avif',
		[2048, 1024],
	],
	[
		'2014-03-23_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_161416.avif',
		[2048, 1024],
	],
	[
		'2014-03-23_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_171312.avif',
		[2048, 1024],
	],
	[
		'2014-03-23_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_190043.avif',
		[2048, 1024],
	],
	[
		'2014-03-23_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_202421.avif',
		[2048, 1024],
	],
	[
		'2014-03-28_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_140346.avif',
		[2048, 1024],
	],
	[
		'2014-03-28_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_140431.avif',
		[2048, 1024],
	],
	[
		'2014-03-28_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_140449.avif',
		[2048, 1024],
	],
	[
		'2014-03-28_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_144028.avif',
		[2048, 1024],
	],
	[
		'2014-03-28_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_151422.avif',
		[2048, 1024],
	],
	[
		'2014-03-28_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_153144.avif',
		[2048, 1024],
	],
	[
		'2014-03-28_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_153200.avif',
		[2048, 1024],
	],
	[
		'2014-03-29_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_131925.avif',
		[2048, 1024],
	],
	[
		'2014-03-29_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_131941.avif',
		[2048, 1024],
	],
	[
		'2014-03-29_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_172611.avif',
		[2048, 1024],
	],
	[
		'2014-03-29_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_175106.avif',
		[2048, 1024],
	],
	[
		'2014-03-29_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_182642.avif',
		[2048, 1024],
	],
	[
		'2014-03-29_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_191231.avif',
		[2048, 1024],
	],
	[
		'2014-03-30_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_135911.avif',
		[2048, 1024],
	],
	[
		'2014-03-30_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_135915.avif',
		[2048, 1024],
	],
	[
		'2014-03-30_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_140832.avif',
		[2048, 1024],
	],
	[
		'2014-03-30_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_141614.avif',
		[2048, 1024],
	],
	[
		'2014-03-30_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_155731.avif',
		[2048, 1024],
	],
	[
		'2014-03-30_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_155806.avif',
		[2048, 1024],
	],
	[
		'2014-03-30_med_562-katie_bauers_breakup_film-behind_the_scenes_set_photo_155814.avif',
		[2048, 1024],
	],
	[
		'2014-04-10_art_300-project_3-disturbance-stillframe_of_character_walking_in_hand_drawn_scene.avif',
		[1920, 1024],
	],
	[
		'2014-05-02_boy_scouts_of_america_marketing_booklet_spec_graphic_design-multiple_pages_layout.avif',
		[1920, 1024],
	],
	[
		'2014-05-03_what_makes_us_human-behind_the_scenes_set_photo_stillframe-green_screen.avif',
		[1536, 768],
	],
	[
		'2014-05-08_video_shoot_behind_the_scenes-green_screen_shoot_at_dorm.avif',
		[2048, 1024],
	],
	['2014-05-15_katie_bauers_breakup-film_poster.avif', [2048, 640]],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-001.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-002.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-057.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-058.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-059.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-060.avif',
		[2048, 640],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-061.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-062.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-063.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-064.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-072.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-084.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-088.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-089.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-092.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-093.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-094.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-095.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-096.avif',
		[2048, 640],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-101.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-103.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-105.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-106.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-112.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-114.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-127.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-128.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-140.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-149.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-150.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-155.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-163.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-165.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-191.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-193.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-194.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-196.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-203.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-212.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-223.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-233.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-251.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-254.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-255.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-269.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-270.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-273.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-281.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-284.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-297.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-306.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-312.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-313.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-318.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-323.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-324.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-334.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-335.avif',
		[2048, 1024],
	],
	[
		'2014-06-04_what_makes_us_human-behind_the_scenes_set_photo_stillframe-344.avif',
		[2048, 1024],
	],
	['2014-06-04_what_makes_us_human-concept_art-telescan_building.avif', [2048, 1024]],
	[
		'2014-06-04_what_makes_us_human-film_poster-villain_in_times_magazine.avif',
		[1365, 683],
	],
	['2014-06-04_what_makes_us_human-film_poster-villian.avif', [1167, 663]],
	['2014-06-04_what_makes_us_human-film_poster_with_text.avif', [1536, 768]],
	['2014-06-04_what_makes_us_human-film_poster_without_text.avif', [1536, 768]],
	['2014-06-04_what_makes_us_human-indiegogo_campaign_team_photo.avif', [1920, 1024]],
	[
		'2014-06-16_video_shoot_behind_the_scenes-green_screen_shoot_of_music_video_at_church.avif',
		[2048, 1024],
	],
	[
		'2014-07-22_what_makes_us_human-behind_the_scenes_set_photo_stillframe_05.avif',
		[2048, 1024],
	],
	['2014-09-15_med_465-one_up-behind_the_scenes_set_photo_03.avif', [2048, 1024]],
	[
		'2014-10-01_cinematography_class_film_shoot-behind_the_scenes_photo_1.avif',
		[2048, 1024],
	],
	[
		'2014-10-01_cinematography_class_film_shoot-behind_the_scenes_photo_2.avif',
		[2048, 1024],
	],
	[
		'2014-10-03_what_makes_us_human-indiegogo_promo_video_shoot_behind_the_scenes.avif',
		[2048, 1024],
	],
	[
		'2014-10-17_video_shoot_behind_the_scenes-filming_sports_at_missouri_state_university.avif',
		[2048, 1024],
	],
	['2014-10-28_mkt_380_graphic_design_assigment-crash_test_dummy_ad.avif', [2048, 1024]],
	['2014-11-01_med_465_film_shoot-behind_the_scenes.avif', [2048, 1024]],
	[
		'2015-01-01_jordan_and_brian_wedding_website-design_with_phone_mockup.avif',
		[1920, 1024],
	],
	[
		'2015-02-07_video_shoot_behind_the_scenes-filming_beheadstrong_promo_video_interview.avif',
		[2048, 1024],
	],
	[
		'2015-04-12_split_life-sato_48-behind_the_scenes-group-planning_session_around_kitchen_table.avif',
		[2048, 1024],
	],
	['2015-04-12_split_life-sato_48-behind_the_scenes-group_meetup.avif', [2048, 1024]],
	['2015-04-12_split_life-sato_48-film_snapshot_1.avif', [2048, 1024]],
	['2015-04-12_split_life-sato_48-film_snapshot_2.avif', [2048, 1024]],
	[
		'2015-04-29_video_shoot_behind_the_scenes-humane_society_promo_video_shoot_1.avif',
		[2048, 1024],
	],
	[
		'2015-04-29_video_shoot_behind_the_scenes-humane_society_promo_video_shoot_2.avif',
		[2048, 1024],
	],
	[
		'2015-05-11_missouri_state_electronic_arts_showcase-what_makes_us_human_premier-crowd.avif',
		[2048, 1024],
	],
	[
		'2015-05-11_missouri_state_electronic_arts_showcase-what_makes_us_human_premier-empty_theater.avif',
		[2048, 1024],
	],
	[
		'2015-05-11_missouri_state_electronic_arts_showcase-what_makes_us_human_premier-what_makes_us_human_crew_group_photo.avif',
		[2048, 1024],
	],
	[
		'2015-05-15_missouri_state_university_graduation-brian_and_jordan_hold_diploma.avif',
		[2048, 1024],
	],
	[
		'2015-05-15_missouri_state_university_graduation-brian_and_jordan_selfie.avif',
		[1920, 1024],
	],
	[
		'2015-06-03_video_shoot_behind_the_scenes-one_year_adventure_novel_promo_video_shoot.avif',
		[2048, 1024],
	],
	[
		'2015-08-13_blue_tape_estate_sales-website_redesign_mockup-home_page.avif',
		[874, 437],
	],
	[
		'2015-08-13_blue_tape_estate_sales-website_redesign_mockup-sales_page.avif',
		[562, 281],
	],
	[
		'2015-08-13_blue_tape_estate_sales-website_redesign_mockup-services_page.avif',
		[562, 281],
	],
	['2016-01-01_brians_computer_setup_2016_with_5_monitors.avif', [2048, 1024]],
	['2016-01-01_diy_camera_mount_1.avif', [2048, 1024]],
	['2016-01-01_diy_camera_mount_2.avif', [2048, 1024]],
	['2016-01-01_diy_led_panels_project.avif', [2048, 1024]],
	['2016-01-01_engagement_grower_infinite_scroll_settings_page_mockup.avif', [1787, 894]],
	['2016-01-01_engagement_grower_marketing_website-features_page.avif', [1886, 1024]],
	['2016-01-01_engagement_grower_marketing_website-full_home_page.avif', [1907, 255]],
	['2016-01-01_engagement_grower_marketing_website-home_page.avif', [1898, 1024]],
	['2016-01-01_engagement_grower_settings_page_addons_mockup.avif', [1787, 894]],
	['2016-01-01_engagement_grower_settings_page_mockup.avif', [1787, 894]],
	[
		'2016-01-01_one_part_laugh_one_part_life_podcast_website_design_mockup_with_tablet_and_phone.avif',
		[1920, 1024],
	],
	['2016-01-01_tower_of_the_americas_panorama-equirectangular.avif', [2048, 1024]],
	['2016-01-01_tower_of_the_americas_panorama-little_planet.avif', [2048, 1024]],
	['2016-01-01_tower_of_the_americas_panorama_app_flow_chart.avif', [1920, 1024]],
	[
		'2016-01-01_tower_of_the_americas_panorama_app_screenshot_page_a1-home_page.avif',
		[1920, 1024],
	],
	[
		'2016-01-01_tower_of_the_americas_panorama_app_screenshot_page_b1-location_selection.avif',
		[1920, 1024],
	],
	[
		'2016-01-01_tower_of_the_americas_panorama_app_screenshot_page_c1-tower_base_page.avif',
		[1920, 1024],
	],
	[
		'2016-01-01_tower_of_the_americas_panorama_app_screenshot_page_c2-observation_deck_page.avif',
		[1920, 1024],
	],
	[
		'2016-01-01_tower_of_the_americas_panorama_app_screenshot_page_d1-compass_selection_page.avif',
		[1920, 1024],
	],
	[
		'2016-01-01_tower_of_the_americas_panorama_app_screenshot_page_d2-find_specific_location_page.avif',
		[1920, 1024],
	],
	[
		'2016-01-01_tower_of_the_americas_panorama_app_screenshot_page_d3-view_story_page.avif',
		[1920, 1024],
	],
	[
		'2016-01-01_tower_of_the_americas_panorama_app_screenshot_page_e1-panorama_page.avif',
		[1920, 1024],
	],
	[
		'2016-01-01_tower_of_the_americas_panorama_app_screenshot_page_e1-panorama_page_zoomed_in.avif',
		[1920, 1024],
	],
	[
		'2016-01-01_tower_of_the_americas_panorama_app_screenshot_page_f1-location_hint_page.avif',
		[1920, 1024],
	],
	[
		'2016-01-01_tower_of_the_americas_panorama_app_screenshot_page_g1-location_info_page.avif',
		[1920, 1024],
	],
	['2016-01-11_bass_factory_album_cover-back_to_bassics.avif', [2048, 1024]],
	['2016-04-25_121_kickstarter_video-360_equirectangular_snapshot.avif', [1920, 1024]],
	['2016-04-25_121_kickstarter_video-360_sphere_snapshot.avif', [1920, 1024]],
	[
		'2016-04-25_121_kickstarter_video-phone_screen_replacement_visual_effect_snapshot.avif',
		[1920, 1024],
	],
	['2016-04-25_121_kickstarter_video-ui_animation_snapshot_1.avif', [1920, 1024]],
	['2016-04-25_bee_stream_app_wireframe_mockup.avif', [1920, 1024]],
	[
		'2016-07-07_video_shoot_behind_the_scenes-church_video_set_photo_with_lights.avif',
		[2048, 1024],
	],
	[
		'2017-01-01_wyoti_digital_marketing_website_design-rotated_page_graphic.avif',
		[2048, 1024],
	],
	['2018-01-01_bassless_ideas_website_design_v1.avif', [933, 467]],
	['2018-01-01_bassless_ideas_website_design_v2.avif', [597, 371]],
	['2024-01-01_remarkably_organized_app-home_page_screenshot.avif', [1907, 1024]],
	['2024-01-01_remarkably_organized_app-settings_popup_screenshot.avif', [1532, 1024]],
	[
		'2024-01-01_remarkably_organized_planner-picture_of_planner_on_remarkable_device-close_up_on_navigation.avif',
		[2048, 1024],
	],
	[
		'2024-01-01_remarkably_organized_planner-picture_of_planner_on_remarkable_device-shallow_depth_of_field_year_view.avif',
		[2048, 1024],
	],
	[
		'2024-01-01_remarkably_organized_planner-picture_of_planner_on_remarkable_device-title_page_close_up.avif',
		[2048, 1024],
	],
	[
		'2024-01-01_remarkably_organized_planner-picture_of_planner_on_remarkable_device-title_page_full_tablet.avif',
		[2048, 1024],
	],
	[
		'2024-01-01_remarkably_organized_planner-picture_of_planner_on_remarkable_device-year_view.avif',
		[2048, 1024],
	],
	['2024-01-01_scrmbld_word_game-gameplay_screenshot.avif', [1907, 1024]],
	['2024-01-01_scrmbld_word_game-header_graphic.avif', [2048, 1024]],
	['2024-01-01_scrmbld_word_game-home_page_screenshot.avif', [1907, 1024]],
	['2024-01-01_scrmbld_word_game-logo-card.avif', [2048, 1024]],
	['2026-01-01_show_and_tour-brand_style_guide-app_icon_mockup.avif', [2048, 1024]],
	['2026-01-01_show_and_tour-brand_style_guide-business_card_mockup.avif', [2048, 1024]],
	['2026-01-01_show_and_tour-brand_style_guide-first_page.avif', [2048, 1024]],
	['2026-01-01_show_and_tour-brand_style_guide-instagram_ad_mockup.avif', [2048, 1024]],
	['2026-01-01_show_and_tour-brand_style_guide-laptop_mockup.avif', [2048, 1024]],
	['2026-01-01_show_and_tour-brand_style_guide-website_mockup.avif', [2048, 1024]],
	['2026-01-01_show_and_tour-dashboard_mockup-clients_page_empty.avif', [2048, 1024]],
	['2026-01-01_show_and_tour-dashboard_mockup-delivery_page_dark.avif', [733, 367]],
	[
		'2026-01-01_show_and_tour-dashboard_mockup-experimental_delivery_page_with_grid_layout.avif',
		[428, 214],
	],
	[
		'2026-01-01_show_and_tour-dashboard_mockup-legacy_delivery_page_preview.avif',
		[1220, 610],
	],
	['2026-01-01_show_and_tour-dashboard_mockup-media_player.avif', [1440, 1024]],
	['2026-01-01_show_and_tour-dashboard_mockup-projects_page_empty.avif', [2048, 1024]],
	['2026-01-01_show_and_tour-dashboard_mockup-signin_page.avif', [2048, 640]],
	[
		'2026-01-01_show_and_tour-dashboard_screenshot-dark_mode_project_client_page.avif',
		[1907, 1024],
	],
	[
		'2026-01-01_show_and_tour-dashboard_screenshot-dark_mode_project_list.avif',
		[1904, 1024],
	],
	[
		'2026-01-01_show_and_tour-dashboard_screenshot-dark_mode_project_page.avif',
		[1890, 1024],
	],
	[
		'2026-01-01_show_and_tour-dashboard_screenshot-dark_mode_settings_page.avif',
		[1907, 1024],
	],
	[
		'2026-01-01_show_and_tour-legacy_delivery_page_screenshot-963_n1950_rd.avif',
		[702, 351],
	],
	[
		'2026-01-01_show_and_tour-property_website_screenshot-8700leeboulevard.avif',
		[854, 427],
	],
	[
		'2026-01-01_show_and_tour-property_website_screenshot-prairievillageestate.avif',
		[1375, 688],
	],
	['2026-01-01_show_and_tour-website_screenshot-home_page-portrait.avif', [1897, 1024]],
	['2026-01-01_show_and_tour-website_screenshot-home_page.avif', [1890, 1024]],
	['2026-01-01_video_curator_screenshot-clips_page.avif', [1920, 1024]],
	['2026-01-01_video_curator_screenshot-dashboard.avif', [1920, 1024]],
	['2026-07-17_family_photo_in_arkansas.avif', [2048, 1024]],
]);
