name = "brianschwabauer"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "92cb4bb9b2a55d24f5688f2f61864079"

[[kv_namespaces]]
binding = "KV"
id = "0b2ff2ae425c43259c71f137972d3691"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "R2"
bucket_name = "brianschwabauer"

[[send_email]]
name = "SEND_EMAIL"
destination_address = "brian@brianschwabauer.com"
