// Regenerates src/lib/components/about/animated-clips.ts — the list of media/
// AVIF files that are ANIMATED (image sequences, brand `avis` in the ftyp box).
// The clip governor uses it to know which <img>s are playing clips without
// fetching bytes at runtime. Run after adding new media:
//
//   node scripts/animated-avifs.mjs
import { readdirSync, openSync, readSync, closeSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const media_dir = join(root, 'media');
const out_path = join(root, 'src/lib/components/about/animated-clips.ts');

function isAnimated(path) {
	// The ftyp box opens the file; `avis` as major or compatible brand marks an
	// AVIF image sequence. 64 bytes is comfortably past every brand list.
	const buf = Buffer.alloc(64);
	const fd = openSync(path, 'r');
	const n = readSync(fd, buf, 0, 64, 0);
	closeSync(fd);
	return buf.subarray(0, n).includes('avis');
}

const names = readdirSync(media_dir, { withFileTypes: true })
	.filter(
		(e) => e.isFile() && e.name.endsWith('.avif') && isAnimated(join(media_dir, e.name)),
	)
	.map((e) => e.name)
	.sort();

const body = `// GENERATED by scripts/animated-avifs.mjs — do not edit by hand.
// Basenames of every animated AVIF in media/ (${names.length} of the full set).
export const ANIMATED_CLIPS = new Set<string>([
${names.map((n) => `\t${JSON.stringify(n)},`).join('\n')}
]);
`;
writeFileSync(out_path, body);
console.log(`${names.length} animated AVIFs → ${out_path}`);
