// Generates a single <name>-thumb.avif (longest side 1024) beside every LARGE
// still AVIF in media/, and regenerates the manifest the components use to
// build srcset strings: src/lib/components/about/media-thumbs.ts.
//
// Only stills ≥ 1400px on their longest side get a thumb — below that the
// full file is already close enough to the thumb size to not be worth a
// second variant. Animated clips are excluded (they are covered by the mp4
// pipeline in scripts/clip-videos.mjs), as are existing -thumb files.
// 1024 rather than a smaller size on purpose: browsers multiply `sizes` by
// devicePixelRatio when picking from srcset, and a ~3× phone would skip
// anything much smaller for a full-width slot — 1024 is the largest "small"
// that phones will actually select, and still ¼ the decode memory of 2048.
//
//   node scripts/media-thumbs.mjs
import { readdirSync, existsSync, statSync, readFileSync, writeFileSync } from 'node:fs';
import { execFile } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import { cpus } from 'node:os';

const run = promisify(execFile);
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const media_dir = join(root, 'media');
const out_path = join(root, 'src/lib/components/about/media-thumbs.ts');

const MIN_SIDE = 1400;
const THUMB_SIDE = 1024;

const animated = new Set(
	[
		...readFileSync(
			join(root, 'src/lib/components/about/animated-clips.ts'),
			'utf8',
		).matchAll(/"([^"]+\.avif)"/g),
	].map((m) => m[1]),
);

const stills = readdirSync(media_dir, { withFileTypes: true })
	.filter(
		(e) =>
			e.isFile() &&
			e.name.endsWith('.avif') &&
			!e.name.endsWith('-thumb.avif') &&
			!animated.has(e.name),
	)
	.map((e) => e.name)
	.sort();

/** name → [fullWidth, thumbWidth], only for files that got a thumb */
const entries = [];
let made = 0;
let kept = 0;

async function dims(path) {
	const { stdout } = await run('magick', ['identify', '-format', '%w %h', `${path}[0]`]);
	return stdout.trim().split(' ').map(Number);
}

async function process(name) {
	const src = join(media_dir, name);
	const [w, h] = await dims(src);
	if (Math.max(w, h) < MIN_SIDE) return;
	const thumb_name = name.replace(/\.avif$/, '-thumb.avif');
	const out = join(media_dir, thumb_name);
	if (!existsSync(out) || statSync(out).mtimeMs < statSync(src).mtimeMs) {
		await run('magick', [
			`${src}[0]`,
			'-resize',
			`${THUMB_SIDE}x${THUMB_SIDE}>`,
			'-quality',
			'50',
			out,
		]);
		made++;
	} else {
		kept++;
	}
	const [tw] = await dims(out);
	entries.push([name, w, tw]);
}

const queue = [...stills];
await Promise.all(
	Array.from({ length: Math.max(2, Math.floor(cpus().length / 2)) }, async () => {
		let name;
		while ((name = queue.shift())) {
			try {
				await process(name);
			} catch (err) {
				console.error(`FAILED ${name}: ${err.message}`);
			}
		}
	}),
);

entries.sort((a, b) => (a[0] < b[0] ? -1 : 1));
const body = `// GENERATED by scripts/media-thumbs.mjs — do not edit by hand.
// Large stills in media/ that have a -thumb.avif variant (longest side ${THUMB_SIDE}),
// mapped to [fullWidth, thumbWidth] for srcset width descriptors.
export const MEDIA_THUMBS = new Map<string, [number, number]>([
${entries.map(([n, w, tw]) => `\t[${JSON.stringify(n)}, [${w}, ${tw}]],`).join('\n')}
]);
`;
writeFileSync(out_path, body);
console.log(
	`${entries.length} thumbed (${made} encoded, ${kept} up to date) of ${stills.length} stills → ${out_path}`,
);
