// Generates a 640px '-thumb.avif' sibling for every starfield tile
// (src/lib/components/about/starfield-images.ts) that doesn't have one, and
// regenerates the manifest the pool reads: starfield-images.ts is the full
// 503-name pool, and any tile can land in the initial seeded field — so a
// tile without a thumb ships its full-size original (some are 2048px / 170KB+
// for a slot that renders at ~150px) on a cold page load.
//
// Thumbs the media-thumbs.mjs pipeline already made (1024px, for gallery
// srcsets) are kept as-is — the starfield happily uses them, and the naming
// is identical. Tiles whose original is already ≤ 800px on its longest side
// are left alone: a 640 variant would barely save anything.
//
//   node scripts/starfield-thumbs.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execFile } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import { cpus } from 'node:os';

const run = promisify(execFile);
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const media_dir = join(root, 'media');
const pool_path = join(root, 'src/lib/components/about/starfield-images.ts');
const out_path = join(root, 'src/lib/components/about/starfield-thumbs.ts');

const MIN_SIDE = 800;
const THUMB_SIDE = 640;

const pool = [
	...readFileSync(pool_path, 'utf8').matchAll(/'([^']+\.(?:avif|png|jpe?g))'/g),
]
	.map((m) => m[1])
	.filter((n) => !n.endsWith('-thumb.avif'));

const thumbName = (name) => name.replace(/\.[a-z0-9]+$/i, '-thumb.avif');

async function dims(path) {
	const { stdout } = await run('magick', ['identify', '-format', '%w %h', `${path}[0]`]);
	return stdout.trim().split(' ').map(Number);
}

let made = 0;
let kept = 0;
let skipped_small = 0;
let missing = 0;

async function process(name) {
	const src = join(media_dir, name);
	if (!existsSync(src)) {
		missing++;
		console.error(`MISSING ${name}`);
		return;
	}
	const out = join(media_dir, thumbName(name));
	if (existsSync(out)) {
		kept++;
		return;
	}
	const [w, h] = await dims(src);
	if (Math.max(w, h) < MIN_SIDE) {
		skipped_small++;
		return;
	}
	await run('magick', [
		`${src}[0]`,
		'-resize',
		`${THUMB_SIDE}x${THUMB_SIDE}>`,
		'-quality',
		'50',
		out,
	]);
	made++;
}

const queue = [...pool];
await Promise.all(
	Array.from({ length: Math.max(2, Math.floor(cpus().length / 2)) }, async () => {
		let name;
		while ((name = queue.shift())) {
			try {
				await process(name);
			} catch (err) {
				console.error(`FAILED ${name}: ${err.message}`);
			}
		}
	}),
);

const withThumb = pool.filter((n) => existsSync(join(media_dir, thumbName(n)))).sort();
const body = `// GENERATED by scripts/starfield-thumbs.mjs — do not edit by hand.
// Starfield pool tiles that have a '-thumb.avif' sibling (longest side ${THUMB_SIDE},
// or 1024 where scripts/media-thumbs.mjs made one first; thumb name = original
// with its extension replaced by '-thumb.avif'). Thumbs must be synced to R2 —
// ./scripts/upload-media-variants.sh does it.
export const STARFIELD_THUMBS: ReadonlySet<string> = new Set([
${withThumb.map((n) => `\t'${n}',`).join('\n')}
]);
`;
writeFileSync(out_path, body);
console.log(
	`pool ${pool.length}: made ${made}, kept ${kept}, small ${skipped_small}, missing ${missing} → manifest ${withThumb.length}`,
);
